export const WORLD_CUP_2026_TEAM_COUNT = 48;
export const STICKERS_PER_TEAM = 25;
export const OFFICIAL_STICKER_COUNT = WORLD_CUP_2026_TEAM_COUNT * STICKERS_PER_TEAM;
export const WORLD_CUP_2026_HOST_CITY_COUNT = 16;
export const WORLD_CUP_2026_TOURNAMENT_DAYS = 39;

